/***********************************************************
This procedure is generated by the query 97 template
in TPC-DS. This query is to generate counts of promotional 
sales and total sales, and their ratio from the web channel 
for a particular item category and month to customers in a 
given time zone.
The detail steps for generating the procedure with loops
by transforming CTE query are as follows. CTE table
variable is :dms.
Then, for each scalar parameter that is used in the query
template, the loop, which calculates the query iteratively for
every range of parameter, is inserted. For the experiments
using the benchmark procedures, we created three databases
with different sizes: 10 GB, 50 GB, and 100 GB. Then, we
observed the scalability of the proposed algorithm using
these different database sizes. In addition, we show that the
performance of the algorithm varies according to the table
statistics, even for the same procedure.
***********************************************************/

set schema "TPC10";
call "TPC10_Q97"(1176)
create procedure "TPC10_Q97"(in dmsInfo integer)
as begin
declare dms integer; -- 1176
dms := :dmsInfo;

v0 = select ss_customer_sk, ss_item_sk, ss_sold_date_sk from store_sales ;
v1 = select cs_bill_customer_sk, cs_item_sk, cs_sold_date_sk from catalog_sales ;

while(:dms < 1209) DO
	ssci = ( select ss_customer_sk customer_sk
	      ,ss_item_sk item_sk
	from :v0, date_dim
	where ss_sold_date_sk = d_date_sk
	  and d_month_seq between :dms and :dms + 11
	group by ss_customer_sk
	        ,ss_item_sk);
	        
	csci = ( select cs_bill_customer_sk customer_sk, cs_item_sk item_sk
	from :v1,date_dim
	where cs_sold_date_sk = d_date_sk and d_month_seq between :dms and :dms + 11
	group by cs_bill_customer_sk, cs_item_sk);
	
	select top 100 sum(case when ssci.customer_sk is not null and csci.customer_sk is null then 1 else 0 end) store_only
	      ,sum(case when ssci.customer_sk is null and csci.customer_sk is not null then 1 else 0 end) catalog_only
	      ,sum(case when ssci.customer_sk is not null and csci.customer_sk is not null then 1 else 0 end) store_and_catalog
	from :ssci ssci full outer join :csci csci on (ssci.customer_sk=csci.customer_sk and ssci.item_sk = csci.item_sk); 
	dms = :dms + 11;
end while;
end;        
        
        

